name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Versioning
        run: echo "Versioning"

  unit-test:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - uses: actions/checkout@v4
      - name: Unit Test
        run: echo "Unit Test"

  quality-gate:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v4
      - name: Quality Gate
        run: echo "Quality Gate"

  security:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
      - uses: actions/checkout@v4
      - name: Security
        run: echo "Security"

  docker-build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Docker Build
        run: echo "Docker Build"

  helm-chart-build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Helm Chart Build
        run: echo "Helm Chart Build"

  performance-testing:
    runs-on: ubuntu-latest
    needs: [docker-build, helm-chart-build]
    steps:
      - uses: actions/checkout@v4
      - name: Performance Testing
        run: echo "Performance Testing"

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: performance-testing
    environment: dev-minnal
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Dev
        run: echo "Deploy to Dev"

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Prod
        run: echo "Deploy to Prod"
